AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an ACM Certificate.

Parameters:
  DomainName:
    Type: String
    Description: The primary domain name for the certificate (e.g., example.com).
  SubjectAlternativeNames:
    Type: CommaDelimitedList
    Description: Additional domain names for the certificate (e.g., www.example.com, api.example.com).
  Environment:
    Type: String

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames: !Ref SubjectAlternativeNames
      ValidationMethod: DNS
      Tags:
        - Key: env
          Value: !Ref Environment

Outputs:
  OutputAcm:
    Description: ACM Cert Id
    Value: !Ref Certificate
    Export:
      Name: !Sub ${AWS::Stack}-OnyxCertificate

